In [1]:
import pandas as pd

data = pd.read_csv('data/bbc_news_train.csv')

data
# data["top_10"]

,ArticleId,Text,Category
0,1833,worldcom ex-boss launches defence lawyers defe...,business
1,154,german business confidence slides german busin...,business
2,1101,bbc poll indicates economic gloom citizens in ...,business
3,1976,lifestyle governs mobile choice faster bett...,tech
4,917,enron bosses in $168m payout eighteen former e...,business
...,...,...,...
1485,857,double eviction from big brother model caprice...,entertainment
1486,325,dj double act revamp chart show dj duo jk and ...,entertainment
1487,1590,weak dollar hits reuters revenues at media gro...,business
1488,1587,apple ipod family expands market apple has exp...,tech
1489,538,santy worm makes unwelcome visit thousands of ...,tech

In [2]:
from nltk.sentiment import SentimentIntensityAnalyzer


sia = SentimentIntensityAnalyzer()

data = "i hate this movie"

sentiment = sia.polarity_scores(data)
print(sentiment)

{'neg': 0.649, 'neu': 0.351, 'pos': 0.0, 'compound': -0.5719}

In [12]:
res_df = pd.read_csv("results/enhanced_news.csv")
res_df[res_df["top_10"]==True]

,id,url,date,headline,body,org,topic,sentiment,scandal_distance,top_10
41,1a227d89-5e1b-47c4-a085-e0628d2750c5,https://www.bbc.com/news/articles/cq57vxjvdy4o...,"Sun, 26 Apr 2026 23:16:41 GMT",How climate change threatens the economic back...,The vast Pacific Ocean and the islands dotted ...,"['theInternational Monetary Fund', 'Food and A...",business,0.7908,0.437345,True
48,002b77c6-59ab-40e3-9f96-983a8b084f69,https://www.bbc.com/news/articles/c86d9v28qxxo...,"Sun, 03 May 2026 23:03:41 GMT",The threat to summer holidays looming from jet...,Listen to Theo read this article. Step on to t...,"['Transport and Environment', 'the European Co...",business,-0.9287,0.506500,True
62,0555ba7e-a59c-41f8-8343-8c3be8f86f01,https://www.bbc.com/news/articles/cqjpqynj1nlo...,"Tue, 12 May 2026 17:55:12 GMT","No sign of larger hantavirus outbreak, says UN...","There is ""no sign"" of a larger hantavirus outb...","['the Philippine Embassy', ""the World Health O...",business,-0.9954,0.478965,True
69,6bead30a-5683-4ca9-b65c-0a33c979ba8b,https://www.bbc.com/news/articles/cpqpernnx8xo...,"Tue, 12 May 2026 11:13:54 GMT",France seeks to move beyond colonial ties by m...,Accused of neo-colonial meddling in many Afric...,"['AFP', 'NTV', 'Francophone', 'Control Risks',...",business,0.9783,0.497675,True
156,3cebb3b3-32d0-4b91-a5a7-d4e7d6c71193,https://www.bbc.com/news/articles/c78q5pygn66o...,"Wed, 29 Apr 2026 13:26:08 GMT",Global forest loss slows but El Niño fires cou...,The loss of tropical rainforests slowed last y...,"['the World Resources Institute', 'El Niño', '...",business,0.8817,0.587649,True
158,4217edba-e113-4cbc-bdfc-d683bfff1e6f,https://www.bbc.com/news/articles/cqxl5rjw58po...,"Sun, 26 Apr 2026 23:01:47 GMT",UK's biggest ever environmental pollution clai...,One of the UK's largest chicken producers and ...,"['Avara Foods and Welsh Water', 'Natural Engla...",business,-0.4064,0.436684,True
159,b40a408f-5849-4a34-a56b-2e61ca420677,https://www.bbc.com/news/articles/c6244zv02ero...,"Sun, 26 Apr 2026 06:20:08 GMT",'We're living in a shed because of river pollu...,People living and working in Herefordshire say...,"['Newent', 'the Lugg Moratorium', 'Avara Foods...",politics,0.9767,0.433415,True
166,8a3a2f28-4f7e-49a2-8fb6-c6206f7999ce,https://www.bbc.com/news/articles/cdxpl4w5027o...,"Wed, 13 May 2026 05:01:19 GMT",How air pollution is being monitored,"As part of its Air Day coverage, BBC South vis...","['Canadaor', ""Southampton City Council's"", 'Ha...",business,0.8515,0.483978,True
180,6312f501-f37d-4bc3-9ce4-751977794a6f,https://www.bbc.com/news/articles/c86ey5n9vx9o...,"Wed, 15 Apr 2026 23:20:22 GMT",Why cheap power could matter more than clean p...,"""I'm an early adopter of new technology,"" says...","['The Office of Budget Responsibility', 'Oxfor...",politics,0.9985,0.541183,True
275,85fbd74d-08a6-462e-afa4-119b30004d41,https://www.bbc.com/news/articles/c1k2zekj8y9o...,"Wed, 13 May 2026 21:14:45 GMT",Israeli strikes in southern Lebanon kill 22 pe...,Twenty-two people including eight children hav...,"['National Council for Scientific Research', '...",business,-0.9989,0.484897,True